package exception1;


public class Arithmnetic {
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		
		
		//ARITNMETIC EXCEPTION
		
		
		
		/*try
		{
		int a=2;
		int b=0;
		int c=a/b;
         System.out.println(c);
		}
		catch(ArithmeticException a) {
			System.out.println("exception handled");
		}
		finally
		{
			System.out.println("end of the code");
		}*/
		
		
		
		//ARRAYOUTOFBOUNDS
		
		
		
		
		/*try
		{
		int a[]= {1,2,3,4};
		
			for(int i=0;i<=4;i++)
			{
			System.out.println(a[i]);
			}
		}
			catch(ArrayIndexOutOfBoundsException b) 
			{
				System.out.println("exception handled");
			}
			finally
			{
				System.out.println("end of the code");
			}
	}
}*/
	
		
		
		
		//NULL POINTER EXCEPTION
		try
		{
       String a=null;     
      System.out.println(a.length());
	}
		catch(ArrayIndexOutOfBoundsException b) 
		{
			System.out.println("exception handled");
		}
		finally
		{
			System.out.println("end of the code");
		}
}
}
		

